services:
  database:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pg/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h database -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: ./backend
    command: 
      sh -c "python manage.py makemigrations &&
      python manage.py makemigrations bookingandbilling &&
      python manage.py migrate &&
      python populate.py &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env.dev

  react:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    env_file:
      - .env.dev